### ISSUE TITLE
[Bug] Selecting Colonies with a VPN active Results in Game Crash

### ISSUE THREAD

**Issue by Bobinsz** [KnuckleCracker/CW4-bug-tracker#994]
I've been enjoying CW4 since release. Love the game! 

I've always been able to enjoy the custom, community made, maps via Colonies whilst my VPN has been Enabled in the past. 

However, over the past month or so if I select Colonies, within the landing screen upon game load, the game Immediately crashes. If I disable my VPN, the game doesn't crash. No Issues with Campaign in either state.

This new bug is rather frustrating, as a VPN user... I do Not want to have to disable it to enjoy the Colonies maps & I've never had to in the past.

I've collated the player.log files in two states, first being the state of the file when the game crashed (with VPN Enabled), I've also included the crash dump folder referred to within the player.log file. The second player.log file is after successfully loading Colonies (with VPN Disabled)

Further Testing: 
If turn my VPN off prior to selecting Colonies (so the game doesn't crash). Once I'm on the Colonies dashboard and able to search maps I can re-enable the VPN, back out of colonies and re-enter without a crash, the maps refresh just times out instead of full game crash & all map downloads fail.

I hope I've provided information that's useful to trace and resolve this new bug, any further information required please let me know. 

Many Thanks

Bobs.

[Crash_2021-10-17_000001785.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/7358434/Crash_2021-10-17_000001785.zip)
[Player_Saved_After_Crash_Loading_Of_Colonies_VPN_Enabled.log](https://github.com/KnuckleCracker/CW4-bug-tracker/files/7358435/Player_Saved_After_Crash_Loading_Of_Colonies_VPN_Enabled.log)
![Untitled](https://user-images.githubusercontent.com/92654582/137605229-5437cd9a-032b-4b6f-90dd-98a46dacb6a5.jpg)
[Player_Saved_After_Succesfull_Loading_Of_Colonies_VPN_Disabled.log](https://github.com/KnuckleCracker/CW4-bug-tracker/files/7358436/Player_Saved_After_Succesfull_Loading_Of_Colonies_VPN_Disabled.log)

**Comment by knucracker** [comment]
Try the current beta version for CW4 on steam.  I have just pushed up version 2.2.3 and it includes an updated HTTP package.  Right  click the game in the steam client then select properties and then choose beta.  The game should show version 2.2.3 on the main menu once you have updated.

The crash logs basically just indicated a memory access error.  It has to be inside one of unity's calls at some level, but the HTTP package I use may have triggered it somehow.  So updating that package may avoid the issue.  If the issue is resolved, or not, let me know.

**Comment by Bobinsz** [comment]
Hi, I've updated to latest beta 2.2.3 and the issue is still present, with the same behavior as mentioned above. Game crashes when entering Colonies with a VPN active, no issues with VPN disabled. Also once Colonies have been entered, if VPN is re-enabled the game no longer crashes when transitioning to the main menu and back into Colonies, the map updates just time out instead of a complete crash. 

Incase it's of use I've packaged the crash dump and logs of the test with the beta. 

Cheers

Bobs


[Crash_2021-10-18_151421432.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/7366276/Crash_2021-10-18_151421432.zip)
[Player_beta2.2.3_VPN_Disabled.log](https://github.com/KnuckleCracker/CW4-bug-tracker/files/7366278/Player_beta2.2.3_VPN_Disabled.log)
[Player_beta2.2.3_VPN_Enabled.log](https://github.com/KnuckleCracker/CW4-bug-tracker/files/7366279/Player_beta2.2.3_VPN_Enabled.log)

**Comment by knucracker** [comment]
Which VPN are you using?
I can check to see if there have been any fixes in unity between over the last 6 months or so.  That's about the only other thing I can do.

**Comment by knucracker** [comment]
Putting this here for reference.  This is for the unity editor, but it may also be related to the runtime: https://forum.unity.com/threads/cant-use-unity-with-nordvpn.610114/

**Comment by Bobinsz** [comment]
I'm using MozillaVPN, after reading the thread you've referred to it could indicate an issue with the VPN itself...

I've done some further testing and I've confirmed the issue is with the VPN. It seems the crash is being caused by a recent update to MozillaVPN v2.5.0 - released 16/09/21 which is causing some kind of conflict in the way its handling certain traffic with unity. 

I've confirmed it's the VPN by rolling back my VPN to the pre-update v2.3.0 and everything is stable, able to open up Colonies fine with no crash or any network issues at all, with my VPN Enabled.

I've no idea what they've changed to have caused this. I wrongly assumed it was something within recent game updates and thought I was being helpful in reporting crashes/bugs, I'm sorry to have wasted your precious time.

Many Thanks

Bobs
